name: Deploy

on:
  push:
    branches:
      - master  # main ブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # リポジトリをクローン
    - name: Checkout code
      uses: actions/checkout@v3

    # SSH の秘密鍵をセットアップ
    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # サーバーに rsync でデプロイ
    - name: Deploy files to server
      run: |
        rsync -avz --delete \
          -e "ssh -p ${{ secrets.SSH_PORT }}-o StrictHostKeyChecking=no" \
          ./ \
          deploy@hassaku.tech:/var/www/src/tmanaka.net
